### ISSUE TITLE
createTaskInList missing

### ISSUE THREAD

**Issue by kaffimunster** [namahu/clickupForGoogleAppsScript#4]
I noticed with your recent update that creating a task within a list with clickup.createTaskInList(list id, payload) was removed from the readme.md. I also haven't been able to run this method in my scripts. It gives the error code: `TypeError: clickup.createTaskInList is not a function (line 129, file "Code")`. Is there a new method to create a task? 

Thank you in advanced for your help! I have been using your library for some time and it is such a time saver!

**Comment by kaffimunster** [comment]
After a bit of messing around, I realized that downgrading to version 4 of the ClickUp library in the script editor fixed my issue.

**Comment by namahu** [comment]
@kaffimunster 

Since my English is not good, I'm writing this using DeepL translation.

Thank you for using the library I created!
I'm also relieved to hear that the problem has been resolved.

When we updated the library, we changed the way we call the methods.

Since version 7, you can create tasks with clickup.Tasks.createTaskInList(list id, task name, payload).
